// -----------------------------------------------------------------------------
// MIT License
//
// Copyright (c) 2026 Florian Körner
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// -----------------------------------------------------------------------------

// Code generated by scripts/build.sh from src/*.json; DO NOT EDIT.

// Package styles embeds the DiceBear avatar style definitions.
//
// It is a pure-data package, mirroring the npm (@dicebear/styles), Composer
// (dicebear/styles), PyPI (dicebear-styles), crates.io (dicebear-styles) and
// pub.dev (dicebear_styles) packages: the same source styles under src/, with
// no logic. The core parses and renders these definitions; this package only
// ships the bytes.
//
// Every style is embedded and exposed both as an exported variable (e.g.
// Adventurer) and by name via Get. Go embeds the whole set into the consuming
// binary — there is no per-style opt-in like the Rust crate's features. Unlike
// the npm build, which serves the minified dist/, Go embeds and parses the
// unminified src/ JSON, matching the Python, PHP, Rust and Dart packages.
package styles

import _ "embed"

//go:embed src/adventurer.json
var Adventurer string

//go:embed src/adventurer-neutral.json
var AdventurerNeutral string

//go:embed src/avataaars.json
var Avataaars string

//go:embed src/avataaars-neutral.json
var AvataaarsNeutral string

//go:embed src/big-ears.json
var BigEars string

//go:embed src/big-ears-neutral.json
var BigEarsNeutral string

//go:embed src/big-smile.json
var BigSmile string

//go:embed src/blobs.json
var Blobs string

//go:embed src/bottts.json
var Bottts string

//go:embed src/bottts-neutral.json
var BotttsNeutral string

//go:embed src/constellation.json
var Constellation string

//go:embed src/critters.json
var Critters string

//go:embed src/croodles.json
var Croodles string

//go:embed src/croodles-neutral.json
var CroodlesNeutral string

//go:embed src/disco.json
var Disco string

//go:embed src/dylan.json
var Dylan string

//go:embed src/fun-emoji.json
var FunEmoji string

//go:embed src/glass.json
var Glass string

//go:embed src/glyphs.json
var Glyphs string

//go:embed src/icons.json
var Icons string

//go:embed src/identicon.json
var Identicon string

//go:embed src/initial-face.json
var InitialFace string

//go:embed src/initials.json
var Initials string

//go:embed src/landscape.json
var Landscape string

//go:embed src/loops.json
var Loops string

//go:embed src/lorelei.json
var Lorelei string

//go:embed src/lorelei-neutral.json
var LoreleiNeutral string

//go:embed src/micah.json
var Micah string

//go:embed src/miniavs.json
var Miniavs string

//go:embed src/moods.json
var Moods string

//go:embed src/notionists.json
var Notionists string

//go:embed src/notionists-neutral.json
var NotionistsNeutral string

//go:embed src/open-peeps.json
var OpenPeeps string

//go:embed src/personas.json
var Personas string

//go:embed src/pixel-art.json
var PixelArt string

//go:embed src/pixel-art-neutral.json
var PixelArtNeutral string

//go:embed src/pixelbot.json
var Pixelbot string

//go:embed src/planets.json
var Planets string

//go:embed src/rings.json
var Rings string

//go:embed src/shape-grid.json
var ShapeGrid string

//go:embed src/shapes.json
var Shapes string

//go:embed src/sprouts.json
var Sprouts string

//go:embed src/squircles.json
var Squircles string

//go:embed src/stripes.json
var Stripes string

//go:embed src/thumbs.json
var Thumbs string

//go:embed src/toon-head.json
var ToonHead string

//go:embed src/triangles.json
var Triangles string

//go:embed src/waves.json
var Waves string

//go:embed src/weave.json
var Weave string

// Get returns the raw JSON definition for the named style, or ("", false) if the
// style name is unknown.
func Get(name string) (string, bool) {
	switch name {
	case "adventurer":
		return Adventurer, true
	case "adventurer-neutral":
		return AdventurerNeutral, true
	case "avataaars":
		return Avataaars, true
	case "avataaars-neutral":
		return AvataaarsNeutral, true
	case "big-ears":
		return BigEars, true
	case "big-ears-neutral":
		return BigEarsNeutral, true
	case "big-smile":
		return BigSmile, true
	case "blobs":
		return Blobs, true
	case "bottts":
		return Bottts, true
	case "bottts-neutral":
		return BotttsNeutral, true
	case "constellation":
		return Constellation, true
	case "critters":
		return Critters, true
	case "croodles":
		return Croodles, true
	case "croodles-neutral":
		return CroodlesNeutral, true
	case "disco":
		return Disco, true
	case "dylan":
		return Dylan, true
	case "fun-emoji":
		return FunEmoji, true
	case "glass":
		return Glass, true
	case "glyphs":
		return Glyphs, true
	case "icons":
		return Icons, true
	case "identicon":
		return Identicon, true
	case "initial-face":
		return InitialFace, true
	case "initials":
		return Initials, true
	case "landscape":
		return Landscape, true
	case "loops":
		return Loops, true
	case "lorelei":
		return Lorelei, true
	case "lorelei-neutral":
		return LoreleiNeutral, true
	case "micah":
		return Micah, true
	case "miniavs":
		return Miniavs, true
	case "moods":
		return Moods, true
	case "notionists":
		return Notionists, true
	case "notionists-neutral":
		return NotionistsNeutral, true
	case "open-peeps":
		return OpenPeeps, true
	case "personas":
		return Personas, true
	case "pixel-art":
		return PixelArt, true
	case "pixel-art-neutral":
		return PixelArtNeutral, true
	case "pixelbot":
		return Pixelbot, true
	case "planets":
		return Planets, true
	case "rings":
		return Rings, true
	case "shape-grid":
		return ShapeGrid, true
	case "shapes":
		return Shapes, true
	case "sprouts":
		return Sprouts, true
	case "squircles":
		return Squircles, true
	case "stripes":
		return Stripes, true
	case "thumbs":
		return Thumbs, true
	case "toon-head":
		return ToonHead, true
	case "triangles":
		return Triangles, true
	case "waves":
		return Waves, true
	case "weave":
		return Weave, true
	}
	return "", false
}

// All returns the names of every embedded style, sorted.
//
// Companion to Get: All lists the names, Get fetches one.
func All() []string {
	return []string{
		"adventurer",
		"adventurer-neutral",
		"avataaars",
		"avataaars-neutral",
		"big-ears",
		"big-ears-neutral",
		"big-smile",
		"blobs",
		"bottts",
		"bottts-neutral",
		"constellation",
		"critters",
		"croodles",
		"croodles-neutral",
		"disco",
		"dylan",
		"fun-emoji",
		"glass",
		"glyphs",
		"icons",
		"identicon",
		"initial-face",
		"initials",
		"landscape",
		"loops",
		"lorelei",
		"lorelei-neutral",
		"micah",
		"miniavs",
		"moods",
		"notionists",
		"notionists-neutral",
		"open-peeps",
		"personas",
		"pixel-art",
		"pixel-art-neutral",
		"pixelbot",
		"planets",
		"rings",
		"shape-grid",
		"shapes",
		"sprouts",
		"squircles",
		"stripes",
		"thumbs",
		"toon-head",
		"triangles",
		"waves",
		"weave",
	}
}
