// -----------------------------------------------------------------------------
// MIT License
//
// Copyright (c) 2026 Florian Körner
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// -----------------------------------------------------------------------------

// @generated by scripts/build.sh from src/*.json — do not edit by hand.

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;

namespace DiceBear
{
    /// <summary>
    /// The DiceBear avatar style definitions, embedded in the assembly.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A pure-data package: the same source styles under <c>src/</c> that the
    /// packages for the other languages ship, with no logic. The core parses
    /// and renders these definitions. This package only ships the bytes.
    /// </para>
    /// <para>
    /// The assembly embeds the unminified <c>src/</c> JSON. The minified
    /// <c>dist/</c> copy exists for the browser and ships only on npm. Every
    /// style is embedded, so the assembly carries the whole set: there is no
    /// per-style opt-in like the Rust crate's features, and the trimmer leaves
    /// embedded resources alone.
    /// </para>
    /// <para>
    /// Every member reads its resource on each call and does not cache it. A
    /// definition is a few hundred kilobytes, and the usual path hands it to
    /// <c>Style.Parse</c> once and keeps the parsed style instead, so caching
    /// the raw text here would hold megabytes nobody reads again.
    /// </para>
    /// <para>
    /// The MIT license in this file's header covers this file only. The
    /// embedded style definitions carry their own licenses, listed in
    /// LICENSE.md and in each definition's <c>meta</c> block.
    /// </para>
    /// </remarks>
    public static class Styles
    {
        private const string ResourcePrefix = "DiceBear.Styles.";

        /// <summary>Raw JSON definition of the DiceBear <c>adventurer</c> avatar style.</summary>
        public static string Adventurer => Read("adventurer");

        /// <summary>Raw JSON definition of the DiceBear <c>adventurer-neutral</c> avatar style.</summary>
        public static string AdventurerNeutral => Read("adventurer-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>avataaars</c> avatar style.</summary>
        public static string Avataaars => Read("avataaars");

        /// <summary>Raw JSON definition of the DiceBear <c>avataaars-neutral</c> avatar style.</summary>
        public static string AvataaarsNeutral => Read("avataaars-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>big-ears</c> avatar style.</summary>
        public static string BigEars => Read("big-ears");

        /// <summary>Raw JSON definition of the DiceBear <c>big-ears-neutral</c> avatar style.</summary>
        public static string BigEarsNeutral => Read("big-ears-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>big-smile</c> avatar style.</summary>
        public static string BigSmile => Read("big-smile");

        /// <summary>Raw JSON definition of the DiceBear <c>blobs</c> avatar style.</summary>
        public static string Blobs => Read("blobs");

        /// <summary>Raw JSON definition of the DiceBear <c>bottts</c> avatar style.</summary>
        public static string Bottts => Read("bottts");

        /// <summary>Raw JSON definition of the DiceBear <c>bottts-neutral</c> avatar style.</summary>
        public static string BotttsNeutral => Read("bottts-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>clay</c> avatar style.</summary>
        public static string Clay => Read("clay");

        /// <summary>Raw JSON definition of the DiceBear <c>constellation</c> avatar style.</summary>
        public static string Constellation => Read("constellation");

        /// <summary>Raw JSON definition of the DiceBear <c>critters</c> avatar style.</summary>
        public static string Critters => Read("critters");

        /// <summary>Raw JSON definition of the DiceBear <c>croodles</c> avatar style.</summary>
        public static string Croodles => Read("croodles");

        /// <summary>Raw JSON definition of the DiceBear <c>croodles-neutral</c> avatar style.</summary>
        public static string CroodlesNeutral => Read("croodles-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>cutouts</c> avatar style.</summary>
        public static string Cutouts => Read("cutouts");

        /// <summary>Raw JSON definition of the DiceBear <c>disco</c> avatar style.</summary>
        public static string Disco => Read("disco");

        /// <summary>Raw JSON definition of the DiceBear <c>dylan</c> avatar style.</summary>
        public static string Dylan => Read("dylan");

        /// <summary>Raw JSON definition of the DiceBear <c>fun-emoji</c> avatar style.</summary>
        public static string FunEmoji => Read("fun-emoji");

        /// <summary>Raw JSON definition of the DiceBear <c>gaze</c> avatar style.</summary>
        public static string Gaze => Read("gaze");

        /// <summary>Raw JSON definition of the DiceBear <c>glass</c> avatar style.</summary>
        public static string Glass => Read("glass");

        /// <summary>Raw JSON definition of the DiceBear <c>glyphs</c> avatar style.</summary>
        public static string Glyphs => Read("glyphs");

        /// <summary>Raw JSON definition of the DiceBear <c>icons</c> avatar style.</summary>
        public static string Icons => Read("icons");

        /// <summary>Raw JSON definition of the DiceBear <c>identicon</c> avatar style.</summary>
        public static string Identicon => Read("identicon");

        /// <summary>Raw JSON definition of the DiceBear <c>initial-face</c> avatar style.</summary>
        public static string InitialFace => Read("initial-face");

        /// <summary>Raw JSON definition of the DiceBear <c>initials</c> avatar style.</summary>
        public static string Initials => Read("initials");

        /// <summary>Raw JSON definition of the DiceBear <c>landscape</c> avatar style.</summary>
        public static string Landscape => Read("landscape");

        /// <summary>Raw JSON definition of the DiceBear <c>line-face</c> avatar style.</summary>
        public static string LineFace => Read("line-face");

        /// <summary>Raw JSON definition of the DiceBear <c>loops</c> avatar style.</summary>
        public static string Loops => Read("loops");

        /// <summary>Raw JSON definition of the DiceBear <c>lorelei</c> avatar style.</summary>
        public static string Lorelei => Read("lorelei");

        /// <summary>Raw JSON definition of the DiceBear <c>lorelei-neutral</c> avatar style.</summary>
        public static string LoreleiNeutral => Read("lorelei-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>marbles</c> avatar style.</summary>
        public static string Marbles => Read("marbles");

        /// <summary>Raw JSON definition of the DiceBear <c>micah</c> avatar style.</summary>
        public static string Micah => Read("micah");

        /// <summary>Raw JSON definition of the DiceBear <c>miniavs</c> avatar style.</summary>
        public static string Miniavs => Read("miniavs");

        /// <summary>Raw JSON definition of the DiceBear <c>moods</c> avatar style.</summary>
        public static string Moods => Read("moods");

        /// <summary>Raw JSON definition of the DiceBear <c>notionists</c> avatar style.</summary>
        public static string Notionists => Read("notionists");

        /// <summary>Raw JSON definition of the DiceBear <c>notionists-neutral</c> avatar style.</summary>
        public static string NotionistsNeutral => Read("notionists-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>open-peeps</c> avatar style.</summary>
        public static string OpenPeeps => Read("open-peeps");

        /// <summary>Raw JSON definition of the DiceBear <c>patchwork</c> avatar style.</summary>
        public static string Patchwork => Read("patchwork");

        /// <summary>Raw JSON definition of the DiceBear <c>personas</c> avatar style.</summary>
        public static string Personas => Read("personas");

        /// <summary>Raw JSON definition of the DiceBear <c>pixel-art</c> avatar style.</summary>
        public static string PixelArt => Read("pixel-art");

        /// <summary>Raw JSON definition of the DiceBear <c>pixel-art-neutral</c> avatar style.</summary>
        public static string PixelArtNeutral => Read("pixel-art-neutral");

        /// <summary>Raw JSON definition of the DiceBear <c>pixelbot</c> avatar style.</summary>
        public static string Pixelbot => Read("pixelbot");

        /// <summary>Raw JSON definition of the DiceBear <c>planets</c> avatar style.</summary>
        public static string Planets => Read("planets");

        /// <summary>Raw JSON definition of the DiceBear <c>rings</c> avatar style.</summary>
        public static string Rings => Read("rings");

        /// <summary>Raw JSON definition of the DiceBear <c>shape-grid</c> avatar style.</summary>
        public static string ShapeGrid => Read("shape-grid");

        /// <summary>Raw JSON definition of the DiceBear <c>shapes</c> avatar style.</summary>
        public static string Shapes => Read("shapes");

        /// <summary>Raw JSON definition of the DiceBear <c>sprouts</c> avatar style.</summary>
        public static string Sprouts => Read("sprouts");

        /// <summary>Raw JSON definition of the DiceBear <c>squircles</c> avatar style.</summary>
        public static string Squircles => Read("squircles");

        /// <summary>Raw JSON definition of the DiceBear <c>stripes</c> avatar style.</summary>
        public static string Stripes => Read("stripes");

        /// <summary>Raw JSON definition of the DiceBear <c>thumbs</c> avatar style.</summary>
        public static string Thumbs => Read("thumbs");

        /// <summary>Raw JSON definition of the DiceBear <c>toon-head</c> avatar style.</summary>
        public static string ToonHead => Read("toon-head");

        /// <summary>Raw JSON definition of the DiceBear <c>triangles</c> avatar style.</summary>
        public static string Triangles => Read("triangles");

        /// <summary>Raw JSON definition of the DiceBear <c>voxel-art</c> avatar style.</summary>
        public static string VoxelArt => Read("voxel-art");

        /// <summary>Raw JSON definition of the DiceBear <c>voxel-bot</c> avatar style.</summary>
        public static string VoxelBot => Read("voxel-bot");

        /// <summary>Raw JSON definition of the DiceBear <c>waves</c> avatar style.</summary>
        public static string Waves => Read("waves");

        /// <summary>Raw JSON definition of the DiceBear <c>weave</c> avatar style.</summary>
        public static string Weave => Read("weave");

        /// <summary>
        /// Returns the raw JSON definition for the named style, or
        /// <see langword="null"/> if the style name is unknown.
        /// </summary>
        /// <param name="name">Style name, e.g. <c>"adventurer"</c>.</param>
        /// <remarks>
        /// Companion to <see cref="All"/>: <c>All()</c> lists the names,
        /// <c>Get(name)</c> fetches one.
        /// </remarks>
        public static string? Get(string name)
        {
            switch (name)
            {
                case "adventurer":
                    return Adventurer;
                case "adventurer-neutral":
                    return AdventurerNeutral;
                case "avataaars":
                    return Avataaars;
                case "avataaars-neutral":
                    return AvataaarsNeutral;
                case "big-ears":
                    return BigEars;
                case "big-ears-neutral":
                    return BigEarsNeutral;
                case "big-smile":
                    return BigSmile;
                case "blobs":
                    return Blobs;
                case "bottts":
                    return Bottts;
                case "bottts-neutral":
                    return BotttsNeutral;
                case "clay":
                    return Clay;
                case "constellation":
                    return Constellation;
                case "critters":
                    return Critters;
                case "croodles":
                    return Croodles;
                case "croodles-neutral":
                    return CroodlesNeutral;
                case "cutouts":
                    return Cutouts;
                case "disco":
                    return Disco;
                case "dylan":
                    return Dylan;
                case "fun-emoji":
                    return FunEmoji;
                case "gaze":
                    return Gaze;
                case "glass":
                    return Glass;
                case "glyphs":
                    return Glyphs;
                case "icons":
                    return Icons;
                case "identicon":
                    return Identicon;
                case "initial-face":
                    return InitialFace;
                case "initials":
                    return Initials;
                case "landscape":
                    return Landscape;
                case "line-face":
                    return LineFace;
                case "loops":
                    return Loops;
                case "lorelei":
                    return Lorelei;
                case "lorelei-neutral":
                    return LoreleiNeutral;
                case "marbles":
                    return Marbles;
                case "micah":
                    return Micah;
                case "miniavs":
                    return Miniavs;
                case "moods":
                    return Moods;
                case "notionists":
                    return Notionists;
                case "notionists-neutral":
                    return NotionistsNeutral;
                case "open-peeps":
                    return OpenPeeps;
                case "patchwork":
                    return Patchwork;
                case "personas":
                    return Personas;
                case "pixel-art":
                    return PixelArt;
                case "pixel-art-neutral":
                    return PixelArtNeutral;
                case "pixelbot":
                    return Pixelbot;
                case "planets":
                    return Planets;
                case "rings":
                    return Rings;
                case "shape-grid":
                    return ShapeGrid;
                case "shapes":
                    return Shapes;
                case "sprouts":
                    return Sprouts;
                case "squircles":
                    return Squircles;
                case "stripes":
                    return Stripes;
                case "thumbs":
                    return Thumbs;
                case "toon-head":
                    return ToonHead;
                case "triangles":
                    return Triangles;
                case "voxel-art":
                    return VoxelArt;
                case "voxel-bot":
                    return VoxelBot;
                case "waves":
                    return Waves;
                case "weave":
                    return Weave;
                default:
                    return null;
            }
        }

        /// <summary>
        /// Names of every embedded style, sorted.
        /// </summary>
        /// <remarks>
        /// Companion to <see cref="Get"/>: <c>All()</c> lists the names,
        /// <c>Get(name)</c> fetches one.
        /// </remarks>
        public static IReadOnlyList<string> All()
        {
            return new[]
            {
                "adventurer",
                "adventurer-neutral",
                "avataaars",
                "avataaars-neutral",
                "big-ears",
                "big-ears-neutral",
                "big-smile",
                "blobs",
                "bottts",
                "bottts-neutral",
                "clay",
                "constellation",
                "critters",
                "croodles",
                "croodles-neutral",
                "cutouts",
                "disco",
                "dylan",
                "fun-emoji",
                "gaze",
                "glass",
                "glyphs",
                "icons",
                "identicon",
                "initial-face",
                "initials",
                "landscape",
                "line-face",
                "loops",
                "lorelei",
                "lorelei-neutral",
                "marbles",
                "micah",
                "miniavs",
                "moods",
                "notionists",
                "notionists-neutral",
                "open-peeps",
                "patchwork",
                "personas",
                "pixel-art",
                "pixel-art-neutral",
                "pixelbot",
                "planets",
                "rings",
                "shape-grid",
                "shapes",
                "sprouts",
                "squircles",
                "stripes",
                "thumbs",
                "toon-head",
                "triangles",
                "voxel-art",
                "voxel-bot",
                "waves",
                "weave",
            };
        }

        /// <summary>
        /// Reads one embedded definition as UTF-8 text.
        /// </summary>
        private static string Read(string name)
        {
            var assembly = typeof(Styles).GetTypeInfo().Assembly;
            var resource = ResourcePrefix + name + ".json";

            using (var stream = assembly.GetManifestResourceStream(resource))
            {
                if (stream == null)
                {
                    throw new InvalidOperationException(
                        "Embedded style resource is missing: " + resource);
                }

                // The JSON files are committed without a byte order mark, and
                // BOM detection is switched off so that one appearing in src/
                // would survive into the string instead of being stripped. That
                // keeps the bytes identical to src/*.json on every platform, and
                // it lets tool/CheckParity see the difference: File.ReadAllText
                // does strip a BOM, so the comparison would fail and report it.
                using (var reader = new StreamReader(
                    stream, new UTF8Encoding(false), detectEncodingFromByteOrderMarks: false))
                {
                    return reader.ReadToEnd();
                }
            }
        }
    }
}
