// -----------------------------------------------------------------------------
// MIT License
//
// Copyright (c) 2026 Florian Körner
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// -----------------------------------------------------------------------------

// @generated by scripts/build.sh from src/*.json — do not edit by hand.

//! DiceBear avatar style definitions, embedded at compile time.
//!
//! This is a pure-data crate. It mirrors the npm (`@dicebear/<style>`), Composer,
//! PyPI (`dicebear-styles`), Go and pub.dev (`dicebear_styles`) packages: the
//! same source styles under `src/`, with no logic. The core parses and renders
//! these definitions; this crate only ships the bytes.
//!
//! Each style is gated behind a feature of the same name, so a binary only embeds
//! the styles it opts into:
//!
//! ```toml
//! dicebear-styles = { version = "10", features = ["shapes", "bottts"] }
//! ```
//!
//! Use `all` to pull in every style. Unlike npm — which serves the minified
//! `dist/` over the browser — Rust embeds and parses the JSON at runtime, so the
//! unminified `src/` files are used directly, matching the Python, PHP, Go and
//! Dart packages.

#[cfg(feature = "adventurer")]
pub const ADVENTURER: &str = include_str!("src/adventurer.json");

#[cfg(feature = "adventurer-neutral")]
pub const ADVENTURER_NEUTRAL: &str = include_str!("src/adventurer-neutral.json");

#[cfg(feature = "avataaars")]
pub const AVATAAARS: &str = include_str!("src/avataaars.json");

#[cfg(feature = "avataaars-neutral")]
pub const AVATAAARS_NEUTRAL: &str = include_str!("src/avataaars-neutral.json");

#[cfg(feature = "big-ears")]
pub const BIG_EARS: &str = include_str!("src/big-ears.json");

#[cfg(feature = "big-ears-neutral")]
pub const BIG_EARS_NEUTRAL: &str = include_str!("src/big-ears-neutral.json");

#[cfg(feature = "big-smile")]
pub const BIG_SMILE: &str = include_str!("src/big-smile.json");

#[cfg(feature = "blobs")]
pub const BLOBS: &str = include_str!("src/blobs.json");

#[cfg(feature = "bottts")]
pub const BOTTTS: &str = include_str!("src/bottts.json");

#[cfg(feature = "bottts-neutral")]
pub const BOTTTS_NEUTRAL: &str = include_str!("src/bottts-neutral.json");

#[cfg(feature = "constellation")]
pub const CONSTELLATION: &str = include_str!("src/constellation.json");

#[cfg(feature = "critters")]
pub const CRITTERS: &str = include_str!("src/critters.json");

#[cfg(feature = "croodles")]
pub const CROODLES: &str = include_str!("src/croodles.json");

#[cfg(feature = "croodles-neutral")]
pub const CROODLES_NEUTRAL: &str = include_str!("src/croodles-neutral.json");

#[cfg(feature = "disco")]
pub const DISCO: &str = include_str!("src/disco.json");

#[cfg(feature = "dylan")]
pub const DYLAN: &str = include_str!("src/dylan.json");

#[cfg(feature = "fun-emoji")]
pub const FUN_EMOJI: &str = include_str!("src/fun-emoji.json");

#[cfg(feature = "glass")]
pub const GLASS: &str = include_str!("src/glass.json");

#[cfg(feature = "glyphs")]
pub const GLYPHS: &str = include_str!("src/glyphs.json");

#[cfg(feature = "icons")]
pub const ICONS: &str = include_str!("src/icons.json");

#[cfg(feature = "identicon")]
pub const IDENTICON: &str = include_str!("src/identicon.json");

#[cfg(feature = "initial-face")]
pub const INITIAL_FACE: &str = include_str!("src/initial-face.json");

#[cfg(feature = "initials")]
pub const INITIALS: &str = include_str!("src/initials.json");

#[cfg(feature = "landscape")]
pub const LANDSCAPE: &str = include_str!("src/landscape.json");

#[cfg(feature = "loops")]
pub const LOOPS: &str = include_str!("src/loops.json");

#[cfg(feature = "lorelei")]
pub const LORELEI: &str = include_str!("src/lorelei.json");

#[cfg(feature = "lorelei-neutral")]
pub const LORELEI_NEUTRAL: &str = include_str!("src/lorelei-neutral.json");

#[cfg(feature = "micah")]
pub const MICAH: &str = include_str!("src/micah.json");

#[cfg(feature = "miniavs")]
pub const MINIAVS: &str = include_str!("src/miniavs.json");

#[cfg(feature = "moods")]
pub const MOODS: &str = include_str!("src/moods.json");

#[cfg(feature = "notionists")]
pub const NOTIONISTS: &str = include_str!("src/notionists.json");

#[cfg(feature = "notionists-neutral")]
pub const NOTIONISTS_NEUTRAL: &str = include_str!("src/notionists-neutral.json");

#[cfg(feature = "open-peeps")]
pub const OPEN_PEEPS: &str = include_str!("src/open-peeps.json");

#[cfg(feature = "personas")]
pub const PERSONAS: &str = include_str!("src/personas.json");

#[cfg(feature = "pixel-art")]
pub const PIXEL_ART: &str = include_str!("src/pixel-art.json");

#[cfg(feature = "pixel-art-neutral")]
pub const PIXEL_ART_NEUTRAL: &str = include_str!("src/pixel-art-neutral.json");

#[cfg(feature = "pixelbot")]
pub const PIXELBOT: &str = include_str!("src/pixelbot.json");

#[cfg(feature = "planets")]
pub const PLANETS: &str = include_str!("src/planets.json");

#[cfg(feature = "rings")]
pub const RINGS: &str = include_str!("src/rings.json");

#[cfg(feature = "shape-grid")]
pub const SHAPE_GRID: &str = include_str!("src/shape-grid.json");

#[cfg(feature = "shapes")]
pub const SHAPES: &str = include_str!("src/shapes.json");

#[cfg(feature = "sprouts")]
pub const SPROUTS: &str = include_str!("src/sprouts.json");

#[cfg(feature = "squircles")]
pub const SQUIRCLES: &str = include_str!("src/squircles.json");

#[cfg(feature = "stripes")]
pub const STRIPES: &str = include_str!("src/stripes.json");

#[cfg(feature = "thumbs")]
pub const THUMBS: &str = include_str!("src/thumbs.json");

#[cfg(feature = "toon-head")]
pub const TOON_HEAD: &str = include_str!("src/toon-head.json");

#[cfg(feature = "triangles")]
pub const TRIANGLES: &str = include_str!("src/triangles.json");

#[cfg(feature = "waves")]
pub const WAVES: &str = include_str!("src/waves.json");

/// Returns the raw JSON definition for the named style, or `None` if the style is
/// unknown or its feature is not enabled in this build.
pub fn get(name: &str) -> Option<&'static str> {
    match name {
        #[cfg(feature = "adventurer")]
        "adventurer" => Some(ADVENTURER),
        #[cfg(feature = "adventurer-neutral")]
        "adventurer-neutral" => Some(ADVENTURER_NEUTRAL),
        #[cfg(feature = "avataaars")]
        "avataaars" => Some(AVATAAARS),
        #[cfg(feature = "avataaars-neutral")]
        "avataaars-neutral" => Some(AVATAAARS_NEUTRAL),
        #[cfg(feature = "big-ears")]
        "big-ears" => Some(BIG_EARS),
        #[cfg(feature = "big-ears-neutral")]
        "big-ears-neutral" => Some(BIG_EARS_NEUTRAL),
        #[cfg(feature = "big-smile")]
        "big-smile" => Some(BIG_SMILE),
        #[cfg(feature = "blobs")]
        "blobs" => Some(BLOBS),
        #[cfg(feature = "bottts")]
        "bottts" => Some(BOTTTS),
        #[cfg(feature = "bottts-neutral")]
        "bottts-neutral" => Some(BOTTTS_NEUTRAL),
        #[cfg(feature = "constellation")]
        "constellation" => Some(CONSTELLATION),
        #[cfg(feature = "critters")]
        "critters" => Some(CRITTERS),
        #[cfg(feature = "croodles")]
        "croodles" => Some(CROODLES),
        #[cfg(feature = "croodles-neutral")]
        "croodles-neutral" => Some(CROODLES_NEUTRAL),
        #[cfg(feature = "disco")]
        "disco" => Some(DISCO),
        #[cfg(feature = "dylan")]
        "dylan" => Some(DYLAN),
        #[cfg(feature = "fun-emoji")]
        "fun-emoji" => Some(FUN_EMOJI),
        #[cfg(feature = "glass")]
        "glass" => Some(GLASS),
        #[cfg(feature = "glyphs")]
        "glyphs" => Some(GLYPHS),
        #[cfg(feature = "icons")]
        "icons" => Some(ICONS),
        #[cfg(feature = "identicon")]
        "identicon" => Some(IDENTICON),
        #[cfg(feature = "initial-face")]
        "initial-face" => Some(INITIAL_FACE),
        #[cfg(feature = "initials")]
        "initials" => Some(INITIALS),
        #[cfg(feature = "landscape")]
        "landscape" => Some(LANDSCAPE),
        #[cfg(feature = "loops")]
        "loops" => Some(LOOPS),
        #[cfg(feature = "lorelei")]
        "lorelei" => Some(LORELEI),
        #[cfg(feature = "lorelei-neutral")]
        "lorelei-neutral" => Some(LORELEI_NEUTRAL),
        #[cfg(feature = "micah")]
        "micah" => Some(MICAH),
        #[cfg(feature = "miniavs")]
        "miniavs" => Some(MINIAVS),
        #[cfg(feature = "moods")]
        "moods" => Some(MOODS),
        #[cfg(feature = "notionists")]
        "notionists" => Some(NOTIONISTS),
        #[cfg(feature = "notionists-neutral")]
        "notionists-neutral" => Some(NOTIONISTS_NEUTRAL),
        #[cfg(feature = "open-peeps")]
        "open-peeps" => Some(OPEN_PEEPS),
        #[cfg(feature = "personas")]
        "personas" => Some(PERSONAS),
        #[cfg(feature = "pixel-art")]
        "pixel-art" => Some(PIXEL_ART),
        #[cfg(feature = "pixel-art-neutral")]
        "pixel-art-neutral" => Some(PIXEL_ART_NEUTRAL),
        #[cfg(feature = "pixelbot")]
        "pixelbot" => Some(PIXELBOT),
        #[cfg(feature = "planets")]
        "planets" => Some(PLANETS),
        #[cfg(feature = "rings")]
        "rings" => Some(RINGS),
        #[cfg(feature = "shape-grid")]
        "shape-grid" => Some(SHAPE_GRID),
        #[cfg(feature = "shapes")]
        "shapes" => Some(SHAPES),
        #[cfg(feature = "sprouts")]
        "sprouts" => Some(SPROUTS),
        #[cfg(feature = "squircles")]
        "squircles" => Some(SQUIRCLES),
        #[cfg(feature = "stripes")]
        "stripes" => Some(STRIPES),
        #[cfg(feature = "thumbs")]
        "thumbs" => Some(THUMBS),
        #[cfg(feature = "toon-head")]
        "toon-head" => Some(TOON_HEAD),
        #[cfg(feature = "triangles")]
        "triangles" => Some(TRIANGLES),
        #[cfg(feature = "waves")]
        "waves" => Some(WAVES),
        _ => None,
    }
}

/// Names of every style available in this build (those whose feature is enabled).
///
/// Companion to `get`: `all()` lists the names, `get(name)` fetches one.
pub fn all() -> Vec<&'static str> {
    #[allow(unused_mut)]
    let mut v = Vec::new();
    #[cfg(feature = "adventurer")]
    v.push("adventurer");
    #[cfg(feature = "adventurer-neutral")]
    v.push("adventurer-neutral");
    #[cfg(feature = "avataaars")]
    v.push("avataaars");
    #[cfg(feature = "avataaars-neutral")]
    v.push("avataaars-neutral");
    #[cfg(feature = "big-ears")]
    v.push("big-ears");
    #[cfg(feature = "big-ears-neutral")]
    v.push("big-ears-neutral");
    #[cfg(feature = "big-smile")]
    v.push("big-smile");
    #[cfg(feature = "blobs")]
    v.push("blobs");
    #[cfg(feature = "bottts")]
    v.push("bottts");
    #[cfg(feature = "bottts-neutral")]
    v.push("bottts-neutral");
    #[cfg(feature = "constellation")]
    v.push("constellation");
    #[cfg(feature = "critters")]
    v.push("critters");
    #[cfg(feature = "croodles")]
    v.push("croodles");
    #[cfg(feature = "croodles-neutral")]
    v.push("croodles-neutral");
    #[cfg(feature = "disco")]
    v.push("disco");
    #[cfg(feature = "dylan")]
    v.push("dylan");
    #[cfg(feature = "fun-emoji")]
    v.push("fun-emoji");
    #[cfg(feature = "glass")]
    v.push("glass");
    #[cfg(feature = "glyphs")]
    v.push("glyphs");
    #[cfg(feature = "icons")]
    v.push("icons");
    #[cfg(feature = "identicon")]
    v.push("identicon");
    #[cfg(feature = "initial-face")]
    v.push("initial-face");
    #[cfg(feature = "initials")]
    v.push("initials");
    #[cfg(feature = "landscape")]
    v.push("landscape");
    #[cfg(feature = "loops")]
    v.push("loops");
    #[cfg(feature = "lorelei")]
    v.push("lorelei");
    #[cfg(feature = "lorelei-neutral")]
    v.push("lorelei-neutral");
    #[cfg(feature = "micah")]
    v.push("micah");
    #[cfg(feature = "miniavs")]
    v.push("miniavs");
    #[cfg(feature = "moods")]
    v.push("moods");
    #[cfg(feature = "notionists")]
    v.push("notionists");
    #[cfg(feature = "notionists-neutral")]
    v.push("notionists-neutral");
    #[cfg(feature = "open-peeps")]
    v.push("open-peeps");
    #[cfg(feature = "personas")]
    v.push("personas");
    #[cfg(feature = "pixel-art")]
    v.push("pixel-art");
    #[cfg(feature = "pixel-art-neutral")]
    v.push("pixel-art-neutral");
    #[cfg(feature = "pixelbot")]
    v.push("pixelbot");
    #[cfg(feature = "planets")]
    v.push("planets");
    #[cfg(feature = "rings")]
    v.push("rings");
    #[cfg(feature = "shape-grid")]
    v.push("shape-grid");
    #[cfg(feature = "shapes")]
    v.push("shapes");
    #[cfg(feature = "sprouts")]
    v.push("sprouts");
    #[cfg(feature = "squircles")]
    v.push("squircles");
    #[cfg(feature = "stripes")]
    v.push("stripes");
    #[cfg(feature = "thumbs")]
    v.push("thumbs");
    #[cfg(feature = "toon-head")]
    v.push("toon-head");
    #[cfg(feature = "triangles")]
    v.push("triangles");
    #[cfg(feature = "waves")]
    v.push("waves");
    v
}
