//! # dicebear-styles
//!
//! The official [DiceBear](https://www.dicebear.com) avatar style definitions,
//! shipped as embedded JSON data.
//!
//! A style definition is a JSON document describing how to build an avatar — its
//! available elements, colors, and metadata. This crate is **pure data**: it
//! contains no rendering or avatar-generation logic, mirroring how the npm
//! (`@dicebear/styles`), Composer (`dicebear/styles`), and PyPI
//! (`dicebear-styles`) packages distribute the same JSON. The JSON schema for
//! the definitions lives in the [`@dicebear/schema`](https://github.com/dicebear/schema)
//! package.
//!
//! ## Usage
//!
//! ```
//! // Look up a style by name.
//! let adventurer = dicebear_styles::get("adventurer").unwrap();
//! assert!(!adventurer.is_empty());
//!
//! // Or use the typed accessor.
//! let lorelei = dicebear_styles::lorelei();
//! assert!(!lorelei.is_empty());
//!
//! // List all available style names.
//! assert_eq!(dicebear_styles::names().len(), 37);
//!
//! // Parse a definition into a `serde_json::Value`.
//! let value = dicebear_styles::parsed("initials").unwrap();
//! assert!(value.is_object());
//! ```

// The `STYLES` table and the per-style accessor functions are generated by
// `build.rs` from the repository's `src/*.json` definitions, in sorted order.
include!(concat!(env!("OUT_DIR"), "/styles.rs"));

/// Returns the raw JSON definition for the style with the given `name`, or
/// `None` if no such style exists.
///
/// Names match the definition file stems, e.g. `"adventurer"` or
/// `"big-ears-neutral"`.
pub fn get(name: &str) -> Option<&'static str> {
    // `STYLES` is sorted by name, so a binary search is correct and cheap.
    STYLES
        .binary_search_by(|(candidate, _)| (*candidate).cmp(name))
        .ok()
        .map(|index| STYLES[index].1)
}

/// Returns the sorted list of all available style names.
pub fn names() -> &'static [&'static str] {
    NAMES
}

/// Returns the style with the given `name` parsed into a [`serde_json::Value`],
/// or `None` if no such style exists.
///
/// # Panics
///
/// Panics if an embedded definition is not valid JSON. This cannot happen with
/// the definitions shipped by this crate, which are validated at build time of
/// the underlying packages, but the panic guards against a corrupted build.
pub fn parsed(name: &str) -> Option<serde_json::Value> {
    get(name).map(|raw| serde_json::from_str(raw).expect("embedded style definition is valid JSON"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn there_are_exactly_37_styles() {
        assert_eq!(names().len(), 37);
        assert_eq!(STYLES.len(), 37);
    }

    #[test]
    fn names_are_sorted_and_unique() {
        let names = names();
        let mut sorted = names.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(names, sorted.as_slice());
    }

    #[test]
    fn every_style_returns_non_empty_valid_json() {
        for &name in names() {
            let raw = get(name).unwrap_or_else(|| panic!("missing style: {name}"));
            assert!(!raw.trim().is_empty(), "empty definition for: {name}");

            let value: serde_json::Value = serde_json::from_str(raw)
                .unwrap_or_else(|e| panic!("invalid JSON for {name}: {e}"));
            assert!(value.is_object(), "definition for {name} is not an object");
        }
    }

    #[test]
    fn parsed_matches_get_for_known_and_unknown() {
        assert!(parsed("adventurer").is_some());
        assert!(parsed("does-not-exist").is_none());
        assert!(get("does-not-exist").is_none());
    }

    #[test]
    fn typed_accessors_match_lookup() {
        assert_eq!(adventurer(), get("adventurer").unwrap());
        assert_eq!(big_ears_neutral(), get("big-ears-neutral").unwrap());
        assert_eq!(pixel_art(), get("pixel-art").unwrap());
    }

    #[test]
    fn expected_names_are_present() {
        for name in [
            "adventurer",
            "adventurer-neutral",
            "avataaars",
            "avataaars-neutral",
            "big-ears",
            "big-ears-neutral",
            "big-smile",
            "bottts",
            "bottts-neutral",
            "croodles",
            "croodles-neutral",
            "disco",
            "dylan",
            "fun-emoji",
            "glass",
            "glyphs",
            "icons",
            "identicon",
            "initial-face",
            "initials",
            "lorelei",
            "lorelei-neutral",
            "micah",
            "miniavs",
            "notionists",
            "notionists-neutral",
            "open-peeps",
            "personas",
            "pixel-art",
            "pixel-art-neutral",
            "rings",
            "shape-grid",
            "shapes",
            "stripes",
            "thumbs",
            "toon-head",
            "triangles",
        ] {
            assert!(get(name).is_some(), "expected style missing: {name}");
        }
    }
}
