// Compares every style embedded in DiceBear.Styles against its source file in
// src/, and fails the build when one drifts or no longer resolves.

using System.Reflection;

using DiceBear;

// CheckParity.csproj bakes the repository root in at build time, so the tool
// depends neither on the working directory nor on how deep the build output
// happens to sit.
var root = Assembly.GetExecutingAssembly()
    .GetCustomAttributes<AssemblyMetadataAttribute>()
    .FirstOrDefault(a => a.Key == "RepositoryRoot")?.Value;

if (root is null)
{
    Console.Error.WriteLine(
        "RepositoryRoot assembly metadata is missing (see CheckParity.csproj)");
    return 1;
}

var sourceDir = Path.Combine(root, "src");

if (!Directory.Exists(sourceDir))
{
    Console.Error.WriteLine($"Source directory not found: {sourceDir}");
    return 1;
}

var failed = false;
var checkedCount = 0;

foreach (var name in Styles.All())
{
    var embedded = Styles.Get(name);

    if (embedded is null)
    {
        Console.Error.WriteLine($"{name}: All() lists it, but Get() returns null");
        failed = true;
        continue;
    }

    var sourceFile = Path.Combine(sourceDir, $"{name}.json");

    if (!File.Exists(sourceFile))
    {
        Console.Error.WriteLine($"{name}: src/{name}.json is missing");
        failed = true;
        continue;
    }

    if (embedded != File.ReadAllText(sourceFile))
    {
        Console.Error.WriteLine($"{name}: the embedded copy differs from src/{name}.json");
        failed = true;
        continue;
    }

    checkedCount++;
}

// The other direction: the csproj embeds src/*.json through a glob, while
// All() is generated by scripts/build.sh. A style added without rerunning the
// build ships inside the assembly but stays invisible to callers.
var known = new HashSet<string>(Styles.All());

foreach (var file in Directory.GetFiles(sourceDir, "*.json"))
{
    var name = Path.GetFileNameWithoutExtension(file);

    if (!known.Contains(name))
    {
        Console.Error.WriteLine(
            $"{name}: src/{name}.json is not in All() — rerun scripts/build.sh");
        failed = true;
    }
}

// An unknown name must not resolve to a style, or `Get` would silently hand
// callers the wrong bytes.
if (Styles.Get("does-not-exist") is not null)
{
    Console.Error.WriteLine("Get() returned a style for an unknown name");
    failed = true;
}

if (failed)
{
    return 1;
}

Console.WriteLine($"OK: {checkedCount} styles byte-identical to src/");
return 0;
