//! Build script for `dicebear-styles`.
//!
//! Scans the repository's `src/*.json` style definitions and generates a
//! deterministic, sorted lookup table that embeds each file via `include_str!`.
//! This mirrors how the npm / Composer / PyPI packages ship the same pure JSON
//! data, without hand-maintaining the list of style names.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // The style definitions live one level up, in `<repo>/src/*.json`.
    let src_dir = manifest_dir.join("..").join("src");

    // Re-run when the set of definition files changes.
    println!("cargo:rerun-if-changed={}", src_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    for entry in fs::read_dir(&src_dir)
        .unwrap_or_else(|e| panic!("failed to read style directory {}: {e}", src_dir.display()))
    {
        let path = entry.expect("failed to read directory entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("style file has a non-UTF-8 name")
            .to_owned();

        // Re-run if any individual definition file changes.
        println!("cargo:rerun-if-changed={}", path.display());

        entries.push((name.clone(), format!("../src/{name}.json")));
    }

    // Deterministic, sorted order by style name.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    assert!(
        !entries.is_empty(),
        "no style definitions found in {}",
        src_dir.display()
    );

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs — do not edit.\n\n");

    // `STYLES` is a sorted slice of (name, raw JSON) pairs.
    generated.push_str(
        "/// All embedded style definitions as `(name, raw_json)` pairs, sorted by name.\n",
    );
    generated.push_str("pub(crate) static STYLES: &[(&str, &str)] = &[\n");
    for (name, rel_path) in &entries {
        // `include_str!` in the generated file resolves relative to OUT_DIR, so
        // we anchor each path to `CARGO_MANIFEST_DIR` (resolved at compile time)
        // and walk up to the repo `src/` directory. This stays portable across
        // machines, unlike an absolute build-host path.
        generated.push_str(&format!(
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel_path}\"))),\n"
        ));
    }
    generated.push_str("];\n\n");

    // `NAMES` is the sorted list of style names, derived from the same entries.
    generated.push_str("/// All style names, sorted.\n");
    generated.push_str("pub(crate) static NAMES: &[&str] = &[\n");
    for (name, _) in &entries {
        generated.push_str(&format!("    {name:?},\n"));
    }
    generated.push_str("];\n\n");

    // Generate a typed accessor function per style, e.g. `big_ears_neutral()`.
    for (name, _) in &entries {
        let fn_name = name.replace('-', "_");
        generated.push_str(&format!(
            "/// Returns the raw JSON definition for the `{name}` style.\n"
        ));
        generated.push_str(&format!(
            "pub fn {fn_name}() -> &'static str {{\n    get({name:?}).expect(\"embedded style is always present\")\n}}\n\n"
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = Path::new(&out_dir).join("styles.rs");
    fs::write(&dest, generated).expect("failed to write generated styles.rs");
}
